sudo: required
language: python
python:
  - "3.6"

before_install:
  - pip install Sphinx
  - pip install sphinx_rtd_theme
  - pip install sphinxcontrib-bibtex

script:
  - python setup.py install
  # we need $addFields support in mongomock and it should ignore missing keys (only for the tests)
  - pip install -e git+https://github.com/atrautsch/mongomock.git@\$addFields#egg=mongomock-3.17.2 && python setup.py test
  - cd ./docs && make html

deploy:
  - provider: pages
    github-token: ${GH_TOKEN}
    local-dir: $TRAVIS_BUILD_DIR/docs/build
    skip-cleanup: true  
    on:
      branch: master